// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/xxkun/client/msg/BasePacket.proto

package com.xxkun.client.msg.bean;

public final class BasePacket {
  private BasePacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xxkun.client.msg.bean.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 HEAD = 1;</code>
     * @return The hEAD.
     */
    int getHEAD();

    /**
     * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
     * @return The type.
     */
    com.xxkun.client.msg.bean.BasePacket.Packet.Type getType();

    /**
     * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
     * @return The enum numeric value on the wire for protocolType.
     */
    int getProtocolTypeValue();
    /**
     * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
     * @return The protocolType.
     */
    com.xxkun.client.msg.bean.Protocol.ProtocolType getProtocolType();

    /**
     * <code>int32 bodyLength = 4;</code>
     * @return The bodyLength.
     */
    int getBodyLength();

    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     * @return Whether the protocol field is set.
     */
    boolean hasProtocol();
    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     * @return The protocol.
     */
    com.google.protobuf.Any getProtocol();
    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getProtocolOrBuilder();

    /**
     * <code>.google.protobuf.Any body = 6;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.Any body = 6;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>.google.protobuf.Any body = 6;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code com.xxkun.client.msg.bean.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xxkun.client.msg.bean.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      type_ = 0;
      protocolType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              hEAD_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              protocolType_ = rawValue;
              break;
            }
            case 32: {

              bodyLength_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (protocol_ != null) {
                subBuilder = protocol_.toBuilder();
              }
              protocol_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(protocol_);
                protocol_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxkun.client.msg.bean.BasePacket.internal_static_com_xxkun_client_msg_bean_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxkun.client.msg.bean.BasePacket.internal_static_com_xxkun_client_msg_bean_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxkun.client.msg.bean.BasePacket.Packet.class, com.xxkun.client.msg.bean.BasePacket.Packet.Builder.class);
    }

    /**
     * Protobuf enum {@code com.xxkun.client.msg.bean.Packet.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER = 0;</code>
       */
      SERVER(0),
      /**
       * <code>PEER = 1;</code>
       */
      PEER(1),
      /**
       * <code>CUSTOM = 2;</code>
       */
      CUSTOM(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SERVER = 0;</code>
       */
      public static final int SERVER_VALUE = 0;
      /**
       * <code>PEER = 1;</code>
       */
      public static final int PEER_VALUE = 1;
      /**
       * <code>CUSTOM = 2;</code>
       */
      public static final int CUSTOM_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return SERVER;
          case 1: return PEER;
          case 2: return CUSTOM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.BasePacket.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.xxkun.client.msg.bean.Packet.Type)
    }

    public static final int HEAD_FIELD_NUMBER = 1;
    private int hEAD_;
    /**
     * <code>int32 HEAD = 1;</code>
     * @return The hEAD.
     */
    @java.lang.Override
    public int getHEAD() {
      return hEAD_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.xxkun.client.msg.bean.BasePacket.Packet.Type getType() {
      @SuppressWarnings("deprecation")
      com.xxkun.client.msg.bean.BasePacket.Packet.Type result = com.xxkun.client.msg.bean.BasePacket.Packet.Type.valueOf(type_);
      return result == null ? com.xxkun.client.msg.bean.BasePacket.Packet.Type.UNRECOGNIZED : result;
    }

    public static final int PROTOCOL_TYPE_FIELD_NUMBER = 3;
    private int protocolType_;
    /**
     * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
     * @return The enum numeric value on the wire for protocolType.
     */
    @java.lang.Override public int getProtocolTypeValue() {
      return protocolType_;
    }
    /**
     * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
     * @return The protocolType.
     */
    @java.lang.Override public com.xxkun.client.msg.bean.Protocol.ProtocolType getProtocolType() {
      @SuppressWarnings("deprecation")
      com.xxkun.client.msg.bean.Protocol.ProtocolType result = com.xxkun.client.msg.bean.Protocol.ProtocolType.valueOf(protocolType_);
      return result == null ? com.xxkun.client.msg.bean.Protocol.ProtocolType.UNRECOGNIZED : result;
    }

    public static final int BODYLENGTH_FIELD_NUMBER = 4;
    private int bodyLength_;
    /**
     * <code>int32 bodyLength = 4;</code>
     * @return The bodyLength.
     */
    @java.lang.Override
    public int getBodyLength() {
      return bodyLength_;
    }

    public static final int PROTOCOL_FIELD_NUMBER = 5;
    private com.google.protobuf.Any protocol_;
    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     * @return Whether the protocol field is set.
     */
    @java.lang.Override
    public boolean hasProtocol() {
      return protocol_ != null;
    }
    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public com.google.protobuf.Any getProtocol() {
      return protocol_ == null ? com.google.protobuf.Any.getDefaultInstance() : protocol_;
    }
    /**
     * <code>.google.protobuf.Any protocol = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getProtocolOrBuilder() {
      return getProtocol();
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private com.google.protobuf.Any body_;
    /**
     * <code>.google.protobuf.Any body = 6;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.Any body = 6;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.Any body = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hEAD_ != 0) {
        output.writeInt32(1, hEAD_);
      }
      if (type_ != com.xxkun.client.msg.bean.BasePacket.Packet.Type.SERVER.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (protocolType_ != com.xxkun.client.msg.bean.Protocol.ProtocolType.NONE.getNumber()) {
        output.writeEnum(3, protocolType_);
      }
      if (bodyLength_ != 0) {
        output.writeInt32(4, bodyLength_);
      }
      if (protocol_ != null) {
        output.writeMessage(5, getProtocol());
      }
      if (body_ != null) {
        output.writeMessage(6, getBody());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hEAD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hEAD_);
      }
      if (type_ != com.xxkun.client.msg.bean.BasePacket.Packet.Type.SERVER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (protocolType_ != com.xxkun.client.msg.bean.Protocol.ProtocolType.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, protocolType_);
      }
      if (bodyLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bodyLength_);
      }
      if (protocol_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getProtocol());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxkun.client.msg.bean.BasePacket.Packet)) {
        return super.equals(obj);
      }
      com.xxkun.client.msg.bean.BasePacket.Packet other = (com.xxkun.client.msg.bean.BasePacket.Packet) obj;

      if (getHEAD()
          != other.getHEAD()) return false;
      if (type_ != other.type_) return false;
      if (protocolType_ != other.protocolType_) return false;
      if (getBodyLength()
          != other.getBodyLength()) return false;
      if (hasProtocol() != other.hasProtocol()) return false;
      if (hasProtocol()) {
        if (!getProtocol()
            .equals(other.getProtocol())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHEAD();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PROTOCOL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + protocolType_;
      hash = (37 * hash) + BODYLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getBodyLength();
      if (hasProtocol()) {
        hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
        hash = (53 * hash) + getProtocol().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.BasePacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxkun.client.msg.bean.BasePacket.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xxkun.client.msg.bean.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xxkun.client.msg.bean.Packet)
        com.xxkun.client.msg.bean.BasePacket.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.BasePacket.internal_static_com_xxkun_client_msg_bean_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxkun.client.msg.bean.BasePacket.internal_static_com_xxkun_client_msg_bean_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxkun.client.msg.bean.BasePacket.Packet.class, com.xxkun.client.msg.bean.BasePacket.Packet.Builder.class);
      }

      // Construct using com.xxkun.client.msg.bean.BasePacket.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hEAD_ = 0;

        type_ = 0;

        protocolType_ = 0;

        bodyLength_ = 0;

        if (protocolBuilder_ == null) {
          protocol_ = null;
        } else {
          protocol_ = null;
          protocolBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxkun.client.msg.bean.BasePacket.internal_static_com_xxkun_client_msg_bean_Packet_descriptor;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.BasePacket.Packet getDefaultInstanceForType() {
        return com.xxkun.client.msg.bean.BasePacket.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.BasePacket.Packet build() {
        com.xxkun.client.msg.bean.BasePacket.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.BasePacket.Packet buildPartial() {
        com.xxkun.client.msg.bean.BasePacket.Packet result = new com.xxkun.client.msg.bean.BasePacket.Packet(this);
        result.hEAD_ = hEAD_;
        result.type_ = type_;
        result.protocolType_ = protocolType_;
        result.bodyLength_ = bodyLength_;
        if (protocolBuilder_ == null) {
          result.protocol_ = protocol_;
        } else {
          result.protocol_ = protocolBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxkun.client.msg.bean.BasePacket.Packet) {
          return mergeFrom((com.xxkun.client.msg.bean.BasePacket.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxkun.client.msg.bean.BasePacket.Packet other) {
        if (other == com.xxkun.client.msg.bean.BasePacket.Packet.getDefaultInstance()) return this;
        if (other.getHEAD() != 0) {
          setHEAD(other.getHEAD());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.protocolType_ != 0) {
          setProtocolTypeValue(other.getProtocolTypeValue());
        }
        if (other.getBodyLength() != 0) {
          setBodyLength(other.getBodyLength());
        }
        if (other.hasProtocol()) {
          mergeProtocol(other.getProtocol());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxkun.client.msg.bean.BasePacket.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxkun.client.msg.bean.BasePacket.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hEAD_ ;
      /**
       * <code>int32 HEAD = 1;</code>
       * @return The hEAD.
       */
      @java.lang.Override
      public int getHEAD() {
        return hEAD_;
      }
      /**
       * <code>int32 HEAD = 1;</code>
       * @param value The hEAD to set.
       * @return This builder for chaining.
       */
      public Builder setHEAD(int value) {
        
        hEAD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 HEAD = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHEAD() {
        
        hEAD_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.xxkun.client.msg.bean.BasePacket.Packet.Type getType() {
        @SuppressWarnings("deprecation")
        com.xxkun.client.msg.bean.BasePacket.Packet.Type result = com.xxkun.client.msg.bean.BasePacket.Packet.Type.valueOf(type_);
        return result == null ? com.xxkun.client.msg.bean.BasePacket.Packet.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.xxkun.client.msg.bean.BasePacket.Packet.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.Packet.Type type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int protocolType_ = 0;
      /**
       * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
       * @return The enum numeric value on the wire for protocolType.
       */
      @java.lang.Override public int getProtocolTypeValue() {
        return protocolType_;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
       * @param value The enum numeric value on the wire for protocolType to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolTypeValue(int value) {
        
        protocolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
       * @return The protocolType.
       */
      @java.lang.Override
      public com.xxkun.client.msg.bean.Protocol.ProtocolType getProtocolType() {
        @SuppressWarnings("deprecation")
        com.xxkun.client.msg.bean.Protocol.ProtocolType result = com.xxkun.client.msg.bean.Protocol.ProtocolType.valueOf(protocolType_);
        return result == null ? com.xxkun.client.msg.bean.Protocol.ProtocolType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
       * @param value The protocolType to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolType(com.xxkun.client.msg.bean.Protocol.ProtocolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protocolType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.ProtocolType protocol_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolType() {
        
        protocolType_ = 0;
        onChanged();
        return this;
      }

      private int bodyLength_ ;
      /**
       * <code>int32 bodyLength = 4;</code>
       * @return The bodyLength.
       */
      @java.lang.Override
      public int getBodyLength() {
        return bodyLength_;
      }
      /**
       * <code>int32 bodyLength = 4;</code>
       * @param value The bodyLength to set.
       * @return This builder for chaining.
       */
      public Builder setBodyLength(int value) {
        
        bodyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bodyLength = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBodyLength() {
        
        bodyLength_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any protocol_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> protocolBuilder_;
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       * @return Whether the protocol field is set.
       */
      public boolean hasProtocol() {
        return protocolBuilder_ != null || protocol_ != null;
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       * @return The protocol.
       */
      public com.google.protobuf.Any getProtocol() {
        if (protocolBuilder_ == null) {
          return protocol_ == null ? com.google.protobuf.Any.getDefaultInstance() : protocol_;
        } else {
          return protocolBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public Builder setProtocol(com.google.protobuf.Any value) {
        if (protocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          protocol_ = value;
          onChanged();
        } else {
          protocolBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public Builder setProtocol(
          com.google.protobuf.Any.Builder builderForValue) {
        if (protocolBuilder_ == null) {
          protocol_ = builderForValue.build();
          onChanged();
        } else {
          protocolBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public Builder mergeProtocol(com.google.protobuf.Any value) {
        if (protocolBuilder_ == null) {
          if (protocol_ != null) {
            protocol_ =
              com.google.protobuf.Any.newBuilder(protocol_).mergeFrom(value).buildPartial();
          } else {
            protocol_ = value;
          }
          onChanged();
        } else {
          protocolBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public Builder clearProtocol() {
        if (protocolBuilder_ == null) {
          protocol_ = null;
          onChanged();
        } else {
          protocol_ = null;
          protocolBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public com.google.protobuf.Any.Builder getProtocolBuilder() {
        
        onChanged();
        return getProtocolFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getProtocolOrBuilder() {
        if (protocolBuilder_ != null) {
          return protocolBuilder_.getMessageOrBuilder();
        } else {
          return protocol_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : protocol_;
        }
      }
      /**
       * <code>.google.protobuf.Any protocol = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getProtocolFieldBuilder() {
        if (protocolBuilder_ == null) {
          protocolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getProtocol(),
                  getParentForChildren(),
                  isClean());
          protocol_ = null;
        }
        return protocolBuilder_;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.Any body = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xxkun.client.msg.bean.Packet)
    }

    // @@protoc_insertion_point(class_scope:com.xxkun.client.msg.bean.Packet)
    private static final com.xxkun.client.msg.bean.BasePacket.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxkun.client.msg.bean.BasePacket.Packet();
    }

    public static com.xxkun.client.msg.bean.BasePacket.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xxkun.client.msg.bean.BasePacket.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xxkun_client_msg_bean_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xxkun_client_msg_bean_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%com/xxkun/client/msg/BasePacket.proto\022" +
      "\031com.xxkun.client.msg.bean\032\031google/proto" +
      "buf/any.proto\032#com/xxkun/client/msg/Prot" +
      "ocol.proto\"\226\002\n\006Packet\022\014\n\004HEAD\030\001 \001(\005\0224\n\004t" +
      "ype\030\002 \001(\0162&.com.xxkun.client.msg.bean.Pa" +
      "cket.Type\022>\n\rprotocol_type\030\003 \001(\0162\'.com.x" +
      "xkun.client.msg.bean.ProtocolType\022\022\n\nbod" +
      "yLength\030\004 \001(\005\022&\n\010protocol\030\005 \001(\0132\024.google" +
      ".protobuf.Any\022\"\n\004body\030\006 \001(\0132\024.google.pro" +
      "tobuf.Any\"(\n\004Type\022\n\n\006SERVER\020\000\022\010\n\004PEER\020\001\022" +
      "\n\n\006CUSTOM\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.xxkun.client.msg.bean.Protocol.getDescriptor(),
        });
    internal_static_com_xxkun_client_msg_bean_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xxkun_client_msg_bean_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xxkun_client_msg_bean_Packet_descriptor,
        new java.lang.String[] { "HEAD", "Type", "ProtocolType", "BodyLength", "Protocol", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.xxkun.client.msg.bean.Protocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
