// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/xxkun/client/msg/CustomRequest.proto

package com.xxkun.client.msg.bean;

public final class CustomRequest {
  private CustomRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseCustomRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xxkun.client.msg.bean.BaseCustomRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.xxkun.client.msg.bean.BaseCustomRequest}
   */
  public static final class BaseCustomRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xxkun.client.msg.bean.BaseCustomRequest)
      BaseCustomRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseCustomRequest.newBuilder() to construct.
    private BaseCustomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseCustomRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseCustomRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseCustomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxkun.client.msg.bean.CustomRequest.internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxkun.client.msg.bean.CustomRequest.internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.class, com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest)) {
        return super.equals(obj);
      }
      com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest other = (com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xxkun.client.msg.bean.BaseCustomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xxkun.client.msg.bean.BaseCustomRequest)
        com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.CustomRequest.internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxkun.client.msg.bean.CustomRequest.internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.class, com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.Builder.class);
      }

      // Construct using com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxkun.client.msg.bean.CustomRequest.internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest getDefaultInstanceForType() {
        return com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest build() {
        com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest buildPartial() {
        com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest result = new com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest) {
          return mergeFrom((com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest other) {
        if (other == com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xxkun.client.msg.bean.BaseCustomRequest)
    }

    // @@protoc_insertion_point(class_scope:com.xxkun.client.msg.bean.BaseCustomRequest)
    private static final com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest();
    }

    public static com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseCustomRequest>
        PARSER = new com.google.protobuf.AbstractParser<BaseCustomRequest>() {
      @java.lang.Override
      public BaseCustomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseCustomRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseCustomRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCustomRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xxkun.client.msg.bean.CustomRequest.BaseCustomRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/xxkun/client/msg/CustomRequest.pro" +
      "to\022\031com.xxkun.client.msg.bean\"\023\n\021BaseCus" +
      "tomRequestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xxkun_client_msg_bean_BaseCustomRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
