// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/xxkun/client/msg/ServerRequest.proto

package com.xxkun.client.msg.bean;

public final class ServerRequest {
  private ServerRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseServerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xxkun.client.msg.bean.BaseServerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 client_version = 1;</code>
     * @return The clientVersion.
     */
    int getClientVersion();

    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    int getRequestTypeValue();
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
     * @return The requestType.
     */
    com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType getRequestType();

    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
     * @return The type.
     */
    com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType getType();

    /**
     * <code>.google.protobuf.Any message = 5;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.google.protobuf.Any message = 5;</code>
     * @return The message.
     */
    com.google.protobuf.Any getMessage();
    /**
     * <code>.google.protobuf.Any message = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.xxkun.client.msg.bean.BaseServerRequest}
   */
  public static final class BaseServerRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xxkun.client.msg.bean.BaseServerRequest)
      BaseServerRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseServerRequest.newBuilder() to construct.
    private BaseServerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseServerRequest() {
      requestType_ = 0;
      token_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseServerRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseServerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              clientVersion_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (message_ != null) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_BaseServerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.class, com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code com.xxkun.client.msg.bean.BaseServerRequest.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET = 0;</code>
       */
      GET(0),
      /**
       * <code>PUT = 1;</code>
       */
      PUT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GET = 0;</code>
       */
      public static final int GET_VALUE = 0;
      /**
       * <code>PUT = 1;</code>
       */
      public static final int PUT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return PUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.xxkun.client.msg.bean.BaseServerRequest.RequestType)
    }

    /**
     * Protobuf enum {@code com.xxkun.client.msg.bean.BaseServerRequest.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0),
      /**
       * <code>PUNCH = 1;</code>
       */
      PUNCH(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <code>PUNCH = 1;</code>
       */
      public static final int PUNCH_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return PUNCH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.getDescriptor().getEnumTypes().get(1);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.xxkun.client.msg.bean.BaseServerRequest.MessageType)
    }

    public static final int CLIENT_VERSION_FIELD_NUMBER = 1;
    private int clientVersion_;
    /**
     * <code>int32 client_version = 1;</code>
     * @return The clientVersion.
     */
    @java.lang.Override
    public int getClientVersion() {
      return clientVersion_;
    }

    public static final int REQUEST_TYPE_FIELD_NUMBER = 2;
    private int requestType_;
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
     * @return The requestType.
     */
    @java.lang.Override public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType result = com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.valueOf(requestType_);
      return result == null ? com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.UNRECOGNIZED : result;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType getType() {
      @SuppressWarnings("deprecation")
      com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType result = com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.valueOf(type_);
      return result == null ? com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private com.google.protobuf.Any message_;
    /**
     * <code>.google.protobuf.Any message = 5;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.google.protobuf.Any message = 5;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.Any getMessage() {
      return message_ == null ? com.google.protobuf.Any.getDefaultInstance() : message_;
    }
    /**
     * <code>.google.protobuf.Any message = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getMessageOrBuilder() {
      return getMessage();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientVersion_ != 0) {
        output.writeInt32(1, clientVersion_);
      }
      if (requestType_ != com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.GET.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (type_ != com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.HEARTBEAT.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (message_ != null) {
        output.writeMessage(5, getMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientVersion_);
      }
      if (requestType_ != com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.GET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (type_ != com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (message_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest)) {
        return super.equals(obj);
      }
      com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest other = (com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest) obj;

      if (getClientVersion()
          != other.getClientVersion()) return false;
      if (requestType_ != other.requestType_) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (type_ != other.type_) return false;
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion();
      hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xxkun.client.msg.bean.BaseServerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xxkun.client.msg.bean.BaseServerRequest)
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_BaseServerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.class, com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.Builder.class);
      }

      // Construct using com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientVersion_ = 0;

        requestType_ = 0;

        token_ = "";

        type_ = 0;

        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          message_ = null;
          messageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest getDefaultInstanceForType() {
        return com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest build() {
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest buildPartial() {
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest result = new com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest(this);
        result.clientVersion_ = clientVersion_;
        result.requestType_ = requestType_;
        result.token_ = token_;
        result.type_ = type_;
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest) {
          return mergeFrom((com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest other) {
        if (other == com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.getDefaultInstance()) return this;
        if (other.getClientVersion() != 0) {
          setClientVersion(other.getClientVersion());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clientVersion_ ;
      /**
       * <code>int32 client_version = 1;</code>
       * @return The clientVersion.
       */
      @java.lang.Override
      public int getClientVersion() {
        return clientVersion_;
      }
      /**
       * <code>int32 client_version = 1;</code>
       * @param value The clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersion(int value) {
        
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 client_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
       * @return The enum numeric value on the wire for requestType.
       */
      @java.lang.Override public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
       * @param value The enum numeric value on the wire for requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTypeValue(int value) {
        
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
       * @return The requestType.
       */
      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType getRequestType() {
        @SuppressWarnings("deprecation")
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType result = com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.valueOf(requestType_);
        return result == null ? com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
       * @param value The requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestType(com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.RequestType request_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType getType() {
        @SuppressWarnings("deprecation")
        com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType result = com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.valueOf(type_);
        return result == null ? com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.xxkun.client.msg.bean.BaseServerRequest.MessageType type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> messageBuilder_;
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return messageBuilder_ != null || message_ != null;
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       * @return The message.
       */
      public com.google.protobuf.Any getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? com.google.protobuf.Any.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public Builder setMessage(com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public Builder setMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public Builder mergeMessage(com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (message_ != null) {
            message_ =
              com.google.protobuf.Any.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          message_ = null;
          messageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public com.google.protobuf.Any.Builder getMessageBuilder() {
        
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.google.protobuf.Any message = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xxkun.client.msg.bean.BaseServerRequest)
    }

    // @@protoc_insertion_point(class_scope:com.xxkun.client.msg.bean.BaseServerRequest)
    private static final com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest();
    }

    public static com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseServerRequest>
        PARSER = new com.google.protobuf.AbstractParser<BaseServerRequest>() {
      @java.lang.Override
      public BaseServerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseServerRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseServerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseServerRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xxkun.client.msg.bean.ServerRequest.BaseServerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartbeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xxkun.client.msg.bean.HeartbeatMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.xxkun.client.msg.bean.HeartbeatMessage}
   */
  public static final class HeartbeatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xxkun.client.msg.bean.HeartbeatMessage)
      HeartbeatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartbeatMessage.newBuilder() to construct.
    private HeartbeatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartbeatMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartbeatMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.class, com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage)) {
        return super.equals(obj);
      }
      com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage other = (com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xxkun.client.msg.bean.HeartbeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xxkun.client.msg.bean.HeartbeatMessage)
        com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.class, com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.Builder.class);
      }

      // Construct using com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage getDefaultInstanceForType() {
        return com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage build() {
        com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage buildPartial() {
        com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage result = new com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage) {
          return mergeFrom((com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage other) {
        if (other == com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xxkun.client.msg.bean.HeartbeatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.xxkun.client.msg.bean.HeartbeatMessage)
    private static final com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage();
    }

    public static com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartbeatMessage>
        PARSER = new com.google.protobuf.AbstractParser<HeartbeatMessage>() {
      @java.lang.Override
      public HeartbeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartbeatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xxkun.client.msg.bean.ServerRequest.HeartbeatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PunchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xxkun.client.msg.bean.PunchMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @return A list containing the peerId.
     */
    java.util.List<java.lang.Long> getPeerIdList();
    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @return The count of peerId.
     */
    int getPeerIdCount();
    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @param index The index of the element to return.
     * @return The peerId at the given index.
     */
    long getPeerId(int index);
  }
  /**
   * Protobuf type {@code com.xxkun.client.msg.bean.PunchMessage}
   */
  public static final class PunchMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xxkun.client.msg.bean.PunchMessage)
      PunchMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PunchMessage.newBuilder() to construct.
    private PunchMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PunchMessage() {
      peerId_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PunchMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PunchMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                peerId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              peerId_.addLong(input.readUInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                peerId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                peerId_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          peerId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_PunchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxkun.client.msg.bean.ServerRequest.PunchMessage.class, com.xxkun.client.msg.bean.ServerRequest.PunchMessage.Builder.class);
    }

    public static final int PEER_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.LongList peerId_;
    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @return A list containing the peerId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getPeerIdList() {
      return peerId_;
    }
    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @return The count of peerId.
     */
    public int getPeerIdCount() {
      return peerId_.size();
    }
    /**
     * <code>repeated uint64 peer_id = 1;</code>
     * @param index The index of the element to return.
     * @return The peerId at the given index.
     */
    public long getPeerId(int index) {
      return peerId_.getLong(index);
    }
    private int peerIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getPeerIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(peerIdMemoizedSerializedSize);
      }
      for (int i = 0; i < peerId_.size(); i++) {
        output.writeUInt64NoTag(peerId_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < peerId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(peerId_.getLong(i));
        }
        size += dataSize;
        if (!getPeerIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        peerIdMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xxkun.client.msg.bean.ServerRequest.PunchMessage)) {
        return super.equals(obj);
      }
      com.xxkun.client.msg.bean.ServerRequest.PunchMessage other = (com.xxkun.client.msg.bean.ServerRequest.PunchMessage) obj;

      if (!getPeerIdList()
          .equals(other.getPeerIdList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPeerIdCount() > 0) {
        hash = (37 * hash) + PEER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPeerIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xxkun.client.msg.bean.ServerRequest.PunchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xxkun.client.msg.bean.PunchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xxkun.client.msg.bean.PunchMessage)
        com.xxkun.client.msg.bean.ServerRequest.PunchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_PunchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xxkun.client.msg.bean.ServerRequest.PunchMessage.class, com.xxkun.client.msg.bean.ServerRequest.PunchMessage.Builder.class);
      }

      // Construct using com.xxkun.client.msg.bean.ServerRequest.PunchMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        peerId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xxkun.client.msg.bean.ServerRequest.internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.PunchMessage getDefaultInstanceForType() {
        return com.xxkun.client.msg.bean.ServerRequest.PunchMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.PunchMessage build() {
        com.xxkun.client.msg.bean.ServerRequest.PunchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xxkun.client.msg.bean.ServerRequest.PunchMessage buildPartial() {
        com.xxkun.client.msg.bean.ServerRequest.PunchMessage result = new com.xxkun.client.msg.bean.ServerRequest.PunchMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          peerId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.peerId_ = peerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xxkun.client.msg.bean.ServerRequest.PunchMessage) {
          return mergeFrom((com.xxkun.client.msg.bean.ServerRequest.PunchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xxkun.client.msg.bean.ServerRequest.PunchMessage other) {
        if (other == com.xxkun.client.msg.bean.ServerRequest.PunchMessage.getDefaultInstance()) return this;
        if (!other.peerId_.isEmpty()) {
          if (peerId_.isEmpty()) {
            peerId_ = other.peerId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePeerIdIsMutable();
            peerId_.addAll(other.peerId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xxkun.client.msg.bean.ServerRequest.PunchMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xxkun.client.msg.bean.ServerRequest.PunchMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList peerId_ = emptyLongList();
      private void ensurePeerIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          peerId_ = mutableCopy(peerId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @return A list containing the peerId.
       */
      public java.util.List<java.lang.Long>
          getPeerIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(peerId_) : peerId_;
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @return The count of peerId.
       */
      public int getPeerIdCount() {
        return peerId_.size();
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @param index The index of the element to return.
       * @return The peerId at the given index.
       */
      public long getPeerId(int index) {
        return peerId_.getLong(index);
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @param index The index to set the value at.
       * @param value The peerId to set.
       * @return This builder for chaining.
       */
      public Builder setPeerId(
          int index, long value) {
        ensurePeerIdIsMutable();
        peerId_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @param value The peerId to add.
       * @return This builder for chaining.
       */
      public Builder addPeerId(long value) {
        ensurePeerIdIsMutable();
        peerId_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @param values The peerId to add.
       * @return This builder for chaining.
       */
      public Builder addAllPeerId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensurePeerIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peerId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 peer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerId() {
        peerId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xxkun.client.msg.bean.PunchMessage)
    }

    // @@protoc_insertion_point(class_scope:com.xxkun.client.msg.bean.PunchMessage)
    private static final com.xxkun.client.msg.bean.ServerRequest.PunchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xxkun.client.msg.bean.ServerRequest.PunchMessage();
    }

    public static com.xxkun.client.msg.bean.ServerRequest.PunchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PunchMessage>
        PARSER = new com.google.protobuf.AbstractParser<PunchMessage>() {
      @java.lang.Override
      public PunchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PunchMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PunchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PunchMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xxkun.client.msg.bean.ServerRequest.PunchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xxkun_client_msg_bean_BaseServerRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xxkun_client_msg_bean_PunchMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/xxkun/client/msg/ServerRequest.pro" +
      "to\022\031com.xxkun.client.msg.bean\032\031google/pr" +
      "otobuf/any.proto\"\303\002\n\021BaseServerRequest\022\026" +
      "\n\016client_version\030\001 \001(\005\022N\n\014request_type\030\002" +
      " \001(\01628.com.xxkun.client.msg.bean.BaseSer" +
      "verRequest.RequestType\022\r\n\005token\030\003 \001(\t\022F\n" +
      "\004type\030\004 \001(\01628.com.xxkun.client.msg.bean." +
      "BaseServerRequest.MessageType\022%\n\007message" +
      "\030\005 \001(\0132\024.google.protobuf.Any\"\037\n\013RequestT" +
      "ype\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\"\'\n\013MessageType\022\r\n\t" +
      "HEARTBEAT\020\000\022\t\n\005PUNCH\020\001\"\022\n\020HeartbeatMessa" +
      "ge\"\037\n\014PunchMessage\022\017\n\007peer_id\030\001 \003(\004b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xxkun_client_msg_bean_BaseServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xxkun_client_msg_bean_BaseServerRequest_descriptor,
        new java.lang.String[] { "ClientVersion", "RequestType", "Token", "Type", "Message", });
    internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xxkun_client_msg_bean_HeartbeatMessage_descriptor,
        new java.lang.String[] { });
    internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xxkun_client_msg_bean_PunchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xxkun_client_msg_bean_PunchMessage_descriptor,
        new java.lang.String[] { "PeerId", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
